workflows:
  android-workflow:
    name: ConnectHub Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.connecthub.social"
        GOOGLE_PLAY_TRACK: internal
      node: 20.18.0
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: |
          npm ci --legacy-peer-deps
      - name: Install compatible Capacitor CLI
        script: |
          npm install -g @capacitor/cli@6.1.2
      - name: Build frontend only (Vite)
        script: |
          echo "=== Building frontend with Vite ==="
          npx vite build --mode production
      - name: Verify build output
        script: |
          echo "=== Checking build output ==="
          ls -la dist/public/
          echo "=== Key files ==="
          ls -la dist/public/index.html
          ls -la dist/public/assets/
      - name: Try Capacitor copy first
        script: |
          echo "=== Trying Capacitor copy ==="
          npx cap copy android
      - name: Check what was copied
        script: |
          echo "=== Android assets after copy ==="
          ls -la android/app/src/main/assets/
          ls -la android/app/src/main/assets/public/
      - name: Remove existing Android directory
        script: |
          echo "=== Removing incomplete Android directory ==="
          rm -rf android
      - name: Force downgrade Capacitor packages for Java 17
        script: |
          echo "=== Force installing Java 17 compatible Capacitor ==="
          npm install @capacitor/core@6.1.2 @capacitor/cli@6.1.2 @capacitor/android@6.1.2 --force
          npm install @capacitor/keyboard@6.0.1 @capacitor/splash-screen@6.0.1 @capacitor/status-bar@6.0.1 --force
      - name: Capacitor add Android platform
        script: |
          echo "=== Adding Android platform with Java 17 compatible version ==="
          npx cap add android
      - name: Verify Capacitor 6.x installation
        script: |
          echo "=== Checking Capacitor versions ==="
          npx cap --version
          npm list @capacitor/core @capacitor/android @capacitor/cli
          echo "=== Should show version 6.x for Java 17 compatibility ==="
      - name: Verify Android setup
        script: |
          echo "=== Android directory after cap add ==="
          ls -la android/
          echo "=== Checking for gradlew ==="
          ls -la android/gradlew
          echo "=== Checking gradle wrapper ==="
          ls -la android/gradle/wrapper/
      - name: Sync Capacitor with API 35 settings
        script: |
          echo "=== Syncing Capacitor with API 35 config ==="
          npx cap sync android
      - name: Check Gradle build files
        script: |
          cd android
          echo "=== Checking build.gradle files ==="
          ls -la build.gradle
          ls -la app/build.gradle
          echo "=== Gradle wrapper info ==="
          ls -la gradle/wrapper/
      - name: Generate upload keystore for Google Play
        script: |
          cd android
          echo "=== Creating UPLOAD KEYSTORE for Google Play Console ==="
          mkdir -p ~/.android
          rm -f ~/.android/upload-keystore.jks
          keytool -genkey -v -keystore ~/.android/upload-keystore.jks -storepass connecthub123 -alias upload-key -keypass connecthub123 -keyalg RSA -keysize 2048 -validity 25000 -dname "CN=ConnectHub,OU=Mobile,O=ConnectHub,L=New York,ST=NY,C=US"
          echo "=== Upload keystore created successfully ==="
      - name: WORKING API 35 FIX and configure signing  
        script: |
          cd android
          echo "=== WORKING SOLUTION: Direct file replacement ==="
          echo "=== Before: variables.gradle ==="
          cat variables.gradle
          echo "=== DIRECT REPLACEMENT of variables.gradle ==="
          cat > variables.gradle << 'VARS_EOF'
          ext {
              minSdkVersion = 23
              compileSdkVersion = 35
              targetSdkVersion = 35
              androidxActivityVersion = '1.9.2'
              androidxAppCompatVersion = '1.7.0'
              androidxCoordinatorLayoutVersion = '1.2.0'
              androidxCoreVersion = '1.15.0'
              androidxFragmentVersion = '1.8.4'
              coreSplashScreenVersion = '1.0.1'
              androidxWebkitVersion = '1.12.1'
              junitVersion = '4.13.2'
              androidxJunitVersion = '1.2.1'
              androidxEspressoCoreVersion = '3.6.1'
              cordovaAndroidVersion = '10.1.1'
          }
          VARS_EOF
          echo "=== DIRECT REPLACEMENT of app/build.gradle defaultConfig ==="
          # Replace the defaultConfig section with our version
          perl -i -pe 'BEGIN{undef $/;} s/defaultConfig \{[^}]*\}/defaultConfig {
        applicationId "com.connecthub.social"
        minSdkVersion 23
        targetSdkVersion 35
        versionCode 100
        versionName "2.0.0"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        aaptOptions {
             \/\/ Files and dirs to omit from the packaged assets dir, modified to accommodate modern web apps.
             \/\/ Default: https:\/\/android.googlesource.com\/platform\/frameworks\/base\/+\/282e181b58cf72b6ca770dc7ca5f91f135444502\/tools\/aapt\/AaptAssets.cpp#61
            ignoreAssetsPattern "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
        }
    }/smg' app/build.gradle
          # Also force compileSdk to be hardcoded
          perl -i -pe 's/compileSdk rootProject\.ext\.compileSdkVersion/compileSdk 35/g' app/build.gradle
          echo "=== VERIFICATION: What do files contain now? ==="
          echo "--- variables.gradle ---"
          cat variables.gradle
          echo "--- app/build.gradle (relevant parts) ---"
          grep -A 15 -B 5 "compileSdk\|defaultConfig" app/build.gradle
          echo "=== Configuring app signing ==="
          cat >> app/build.gradle << 'EOF'
          
          android {
              signingConfigs {
                  upload {
                      storeFile file(System.getProperty("user.home") + "/.android/upload-keystore.jks")
                      storePassword "connecthub123"
                      keyAlias "upload-key"
                      keyPassword "connecthub123"
                  }
              }
              buildTypes {
                  release {
                      signingConfig signingConfigs.upload
                  }
              }
          }
          EOF
      - name: Clean and build signed release AAB
        script: |
          cd android
          chmod +x gradlew
          echo "=== Cleaning previous build ==="
          ./gradlew clean
          echo "=== Building RELEASE AAB with VERSION 100 ==="
          ./gradlew bundleRelease
          echo "=== CRITICAL: Analyzing built AAB file ==="
          find app/build/outputs -name "*.aab" -exec echo "Found AAB: {}" \;
          echo "=== Extracting AAB contents to check API levels ==="
          find app/build/outputs -name "*.aab" -exec aapt dump badging {} \; | grep -E "compileSdkVersion|targetSdkVersion|sdkVersion|platformBuildVersionName" || echo "Could not extract API info"
          echo "=== Checking AndroidManifest.xml in AAB ==="
          find app/build/outputs -name "*.aab" -exec aapt dump xmltree {} AndroidManifest.xml \; | grep -i sdk || echo "Could not extract manifest"
          echo "=== Verifying AAB is signed ==="
          find app/build/outputs -name "*.aab" -exec jarsigner -verify -verbose {} \;
          echo "=== Build completed - CHECK THE API LEVELS ABOVE ==="
      - name: Find all build outputs
        script: |
          cd android
          echo "=== Searching for all build outputs ==="
          find . -name "*.aab" -type f 2>/dev/null || echo "No .aab files found"
          find . -name "*.apk" -type f 2>/dev/null || echo "No .apk files found"
          echo "=== Build outputs directory structure ==="
          ls -la app/build/outputs/ 2>/dev/null || echo "No outputs directory"
          find app/build/outputs/ -type f 2>/dev/null || echo "No files in outputs"
          echo "=== Complete app/build structure ==="
          find app/build/ -name "*bundle*" -o -name "*aab*" -o -name "*apk*" 2>/dev/null || echo "No bundle/aab/apk files found"
    artifacts:
      - android/app/build/outputs/**/*
      - android/app/build/**/*.aab
      - android/app/build/**/*.apk
    publishing:
      email:
        recipients:
          - your-metealper@gmail.com
        notify:
          success: true
          failure: false
