workflows:
  android-workflow:
    name: ConnectHub Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.connecthub.app"
      node: 20.18.0
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: |
          npm ci --legacy-peer-deps
      - name: Install Capacitor CLI globally
        script: |
          npm install -g @capacitor/cli@latest
      - name: Build frontend only (Vite)
        script: |
          echo "=== Building frontend with Vite ==="
          npx vite build --mode production
      - name: Verify build output
        script: |
          echo "=== Checking build output ==="
          ls -la dist/public/
          echo "=== Key files ==="
          ls -la dist/public/index.html
          ls -la dist/public/assets/
      - name: Try Capacitor copy first
        script: |
          echo "=== Trying Capacitor copy ==="
          npx cap copy android
      - name: Check what was copied
        script: |
          echo "=== Android assets after copy ==="
          ls -la android/app/src/main/assets/
          ls -la android/app/src/main/assets/public/
      - name: Remove existing Android directory
        script: |
          echo "=== Removing incomplete Android directory ==="
          rm -rf android
      - name: Capacitor add Android platform
        script: |
          echo "=== Adding fresh Android platform ==="
          npx cap add android
      - name: Verify Android setup
        script: |
          echo "=== Android directory after cap add ==="
          ls -la android/
          echo "=== Checking for gradlew ==="
          ls -la android/gradlew
          echo "=== Checking gradle wrapper ==="
          ls -la android/gradle/wrapper/
      - name: Copy web assets to Android
        script: |
          echo "=== Copying web assets ==="
          npx cap copy android
      - name: Check Gradle build files
        script: |
          cd android
          echo "=== Checking build.gradle files ==="
          ls -la build.gradle
          ls -la app/build.gradle
          echo "=== Gradle wrapper info ==="
          ls -la gradle/wrapper/
      - name: Clean and build Android AAB
        script: |
          cd android
          chmod +x gradlew
          echo "=== Cleaning previous build ==="
          ./gradlew clean --info
          echo "=== Building Android AAB with full output ==="
          ./gradlew bundleDebug --info --debug 2>&1 | head -100
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your-metealper@gmail.com
        notify:
          success: true
          failure: false
