workflows:
  android-workflow:
    name: ConnectHub Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.connecthub.app"
      node: 20.18.0
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: |
          npm ci --legacy-peer-deps
      - name: Check project structure
        script: |
          echo "=== Project Structure ==="
          ls -la
          echo "=== Client directory ==="
          ls -la client/
      - name: Build frontend only (Vite)
        script: |
          echo "=== Building frontend with Vite ==="
          npx vite build --mode production
      - name: Verify build output
        script: |
          echo "=== Checking build output ==="
          ls -la dist/
          ls -la dist/public/
          echo "=== Build output files ==="
          find dist/public -type f | head -10
      - name: Install Capacitor CLI globally
        script: |
          npm install -g @capacitor/cli@latest
      - name: Capacitor sync with verbose output
        script: |
          echo "=== Running Capacitor sync ==="
          npx cap sync android --verbose
      - name: Verify Android assets
        script: |
          echo "=== Checking Android assets ==="
          ls -la android/app/src/main/assets/
          ls -la android/app/src/main/assets/public/
      - name: Build Android AAB (unsigned)
        script: |
          cd android
          chmod +x gradlew
          echo "=== Building Android AAB ==="
          ./gradlew bundleDebug --stacktrace --info
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your-metealper@gmail.com
        notify:
          success: true
          failure: false
