workflows:
  android-workflow:
    name: ConnectHub Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.connecthub.app"
      node: 20.18.0
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: |
          npm ci --legacy-peer-deps
      - name: Install Capacitor CLI globally
        script: |
          npm install -g @capacitor/cli@latest
      - name: Build frontend first
        script: |
          npm run build
      - name: Capacitor sync with verbose output
        script: |
          npx cap sync android --verbose
      - name: Check Android project structure
        script: |
          ls -la android/
          ls -la android/app/src/main/
      - name: Build Android AAB (unsigned)
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleDebug --stacktrace
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your-metealper@gmail.com
        notify:
          success: true
          failure: false
